### ISSUE TITLE
Item based CF from TEST_MOVIE_ID?

### ISSUE THREAD

**Issue by hanzigs** [nahidalam/blog#1]
That was a great work, Thanks for that. One question.
Like you did for User Based Prediction in 
```
user_embedding = user_model.predict([TEST_USER_ID]).reshape(1,-1)[0]
```
May I know how to do for item based? 
whether like below
```
movie_embedding = movie_model.predict([TEST_MOVIE_ID]).reshape(1,-1)[0]
recommend_movies(movie_embedding)
```
Thanks

**Comment by nahidalam** [comment]
yes that should work.
